'use client';

interface ProposalTemplateProps {
  freelancerName: string;
  clientName: string;
  projectTitle: string;
  content: string;
  date: string;
}

export function ProposalTemplate({
  freelancerName,
  clientName,
  projectTitle,
  content,
  date,
}: ProposalTemplateProps) {
  return (
    <div className="mx-auto max-w-3xl space-y-6 p-8 text-neutral-800">
      <header className="border-b border-neutral-200 pb-4">
        <h1 className="text-xl font-bold text-neutral-900">Project Proposal</h1>
        <p className="text-sm text-neutral-500">
          {projectTitle} &middot; {date}
        </p>
      </header>

      <div className="text-sm leading-relaxed whitespace-pre-wrap">{content}</div>

      <footer className="border-t border-neutral-200 pt-4 text-xs text-neutral-400">
        <p>Prepared by {freelancerName} for {clientName}</p>
        <p>Generated by KolaAgent &middot; Kolaborate Africa</p>
      </footer>
    </div>
  );
}
