'use client';

import type { PDFSection } from '@/types/pdf';

interface ScopeReportTemplateProps {
  title: string;
  sections: PDFSection[];
  date: string;
}

export function ScopeReportTemplate({ title, sections, date }: ScopeReportTemplateProps) {
  return (
    <div className="mx-auto max-w-3xl space-y-6 p-8 text-neutral-800">
      <header className="border-b border-neutral-200 pb-4">
        <h1 className="text-xl font-bold text-neutral-900">Scope Report</h1>
        <p className="text-sm text-neutral-500">
          {title} &middot; {date}
        </p>
      </header>

      {sections.map((section, i) => (
        <section key={i} className="space-y-2">
          <h2 className="text-base font-semibold text-neutral-900">
            {i + 1}. {section.title}
          </h2>
          <div className="text-sm leading-relaxed whitespace-pre-wrap text-neutral-700">
            {section.content}
          </div>
        </section>
      ))}

      <footer className="border-t border-neutral-200 pt-4 text-xs text-neutral-400">
        <p>Generated by KolaAgent &middot; Kolaborate Africa</p>
      </footer>
    </div>
  );
}
