import type { ExportOptions, PDFSection } from '@/types/pdf';
import { brandColors, fonts, spacing, page } from './styles';

interface PDFLine {
  text: string;
  x: number;
  y: number;
  size: number;
  font: string;
  style: string;
  color: string;
  maxWidth?: number;
}

interface PDFRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string;
}

export class PDFGenerator {
  private lines: PDFLine[] = [];
  private rects: PDFRect[] = [];
  private cursorY = spacing.pageMargin;
  private readonly marginX = spacing.pageMargin;
  private readonly contentWidth = page.width - spacing.pageMargin * 2;

  addSection(title: string, content: string) {
    // Title bar background
    this.rects.push({
      x: this.marginX,
      y: this.cursorY,
      width: this.contentWidth,
      height: 24,
      fill: brandColors.primaryLight,
    });

    this.lines.push({
      text: title,
      x: this.marginX + 8,
      y: this.cursorY + 7,
      size: fonts.subheading.size,
      font: fonts.subheading.font,
      style: fonts.subheading.style,
      color: brandColors.primary,
    });

    this.cursorY += 32;

    // Content paragraphs
    const paragraphs = content.split('\n').filter(Boolean);
    for (const para of paragraphs) {
      const wrapped = this.wrapText(para, this.contentWidth - 16, fonts.body.size);
      for (const line of wrapped) {
        this.checkPageBreak(16);
        this.lines.push({
          text: line,
          x: this.marginX + 8,
          y: this.cursorY,
          size: fonts.body.size,
          font: fonts.body.font,
          style: fonts.body.style,
          color: brandColors.text,
        });
        this.cursorY += 16;
      }
      this.cursorY += spacing.paragraphGap - 16;
    }

    this.cursorY += spacing.sectionGap;
  }

  addHeader(title: string) {
    this.lines.push({
      text: title,
      x: this.marginX,
      y: this.cursorY,
      size: fonts.heading.size,
      font: fonts.heading.font,
      style: fonts.heading.style,
      color: brandColors.primary,
    });
    this.cursorY += 30;

    // Divider line
    this.rects.push({
      x: this.marginX,
      y: this.cursorY,
      width: this.contentWidth,
      height: 2,
      fill: brandColors.primary,
    });
    this.cursorY += 12;
  }

  addFooter() {
    const footerY = page.height - 30;
    this.lines.push({
      text: 'Generated by KolaAgent — Kolaborate Africa',
      x: this.marginX,
      y: footerY,
      size: fonts.small.size,
      font: fonts.small.font,
      style: fonts.small.style,
      color: brandColors.textMuted,
    });
    this.lines.push({
      text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      x: page.width - spacing.pageMargin,
      y: footerY,
      size: fonts.small.size,
      font: fonts.small.font,
      style: fonts.small.style,
      color: brandColors.textMuted,
    });
  }

  addDivider() {
    this.rects.push({
      x: this.marginX,
      y: this.cursorY,
      width: this.contentWidth,
      height: 0.5,
      fill: brandColors.border,
    });
    this.cursorY += 10;
  }

  toJSON(): { lines: PDFLine[]; rects: PDFRect[]; pageWidth: number; pageHeight: number } {
    return {
      lines: this.lines,
      rects: this.rects,
      pageWidth: page.width,
      pageHeight: page.height,
    };
  }

  toHTML(options: ExportOptions): string {
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(options.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Helvetica, Arial, sans-serif; color: ${brandColors.text}; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: ${brandColors.primary}; font-size: 20px; margin-bottom: 8px; border-bottom: 3px solid ${brandColors.primary}; padding-bottom: 8px; }
    h2 { color: ${brandColors.primary}; font-size: 14px; background: ${brandColors.primaryLight}; padding: 8px 12px; border-radius: 4px; margin-top: 24px; margin-bottom: 12px; }
    p { font-size: 11px; line-height: 1.6; margin-bottom: 8px; }
    .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid ${brandColors.border}; font-size: 9px; color: ${brandColors.textMuted}; }
    .header-subtitle { font-size: 11px; color: ${brandColors.textMuted}; margin-bottom: 20px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(options.title)}</h1>
  <p class="header-subtitle">${escapeHtml(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))}</p>
  ${options.sections.map((s) => `<h2>${escapeHtml(s.title)}</h2>${s.content.split('\n').filter(Boolean).map((p) => `<p>${escapeHtml(p)}</p>`).join('\n')}`).join('\n')}
  <div class="footer">Generated by KolaAgent — Kolaborate Africa</div>
</body>
</html>`;
    return html;
  }

  private checkPageBreak(height: number) {
    if (this.cursorY + height > page.height - 50) {
      this.cursorY = spacing.pageMargin + 30;
    }
  }

  private wrapText(text: string, maxWidth: number, fontSize: number): string[] {
    const charsPerLine = Math.floor(maxWidth / (fontSize * 0.55));
    if (text.length <= charsPerLine) return [text];

    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';

    for (const word of words) {
      if (current.length + word.length + 1 > charsPerLine) {
        if (current) lines.push(current);
        current = word;
      } else {
        current = current ? `${current} ${word}` : word;
      }
    }
    if (current) lines.push(current);
    return lines;
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
